fail2ban

diff --git a/modules/configure_fail2ban b/modules/configure_fail2ban
--- a/modules/configure_fail2ban
+++ b/modules/configure_fail2ban
@@ -1,9 +1,11 @@
 # Function to configure fail2ban
 configure_fail2ban() {
+    local max_retries
+    local ban_time
 
     # Create a new configuration file for fail2ban
-    log -e "${BLUE}Configuring fail2ban.${NC}"
-    tee /etc/fail2ban/jail.local >> "$LOG_FILE" 2>&1 <<EOF
+    log "${BLUE}Configuring fail2ban.${NC}"
+    if tee /etc/fail2ban/jail.local >> "$LOG_FILE" 2>&1 <<EOF
     [sshd]
     enabled = true
     port = 22
@@ -12,11 +14,26 @@ configure_fail2ban() {
     maxretry = 10
     bantime = 60m
 EOF
+    then
+        # Restart fail2ban
+        log "Restarting fail2ban..."
+        if systemctl restart fail2ban >> "$LOG_FILE" 2>&1; then
+            log "${BLUE}Fail2ban service restarted.${NC}"
 
-    # Restart fail2ban
-    log "Restarting fail2ban..."
-    systemctl restart fail2ban >> "$LOG_FILE" 2>&1
+            # Extract maxretry and bantime values from the configuration file
+            max_retries=$(grep -Po '(?<=maxretry = )\d+' /etc/fail2ban/jail.local)
+            ban_time=$(grep -Po '(?<=bantime = )\S+' /etc/fail2ban/jail.local)
 
-    log "${BLUE}Fail2ban configuration: ${GREEN}DONE${NC}"
-    echo -e "${BLUE}Fail2ban configuration: ${GREEN}DONE${NC}" >> report.txt
+            log "${BLUE}Fail2ban configuration: ${GREEN}DONE${NC}"
+            echo -e "${BLUE}Fail2ban configuration: ${GREEN}DONE${NC}. ${BLUE}Max Retries: ${ORANGE}${max_retries}${NC},${BLUE}Ban Time: ${ORANGE}${ban_time}${NC}" >> report.txt
+        else
+            log "${RED}Error restarting fail2ban.${NC}"
+            echo -e "${RED}Error restarting fail2ban.${NC}" >> report.txt
+            exit 1
+        fi
+    else
+        log "${RED}Error configuring fail2ban.${NC}"
+        echo -e "${RED}Error configuring fail2ban.${NC}" >> report.txt
+        exit 1
+    fi
 }
diff --git a/modules/configure_iptables_firewall b/modules/configure_iptables_firewall
--- a/modules/configure_iptables_firewall
+++ b/modules/configure_iptables_firewall
@@ -1,6 +1,5 @@
 # Function to configure IP tables firewal
 configure_iptables_firewall() {
-    # Port 80 (HTTP) and Port 22 (SSH)
     log "${BLUE}Configuring iptables firewall${NC}"
 
     # Split the PORTS string into an array
@@ -8,12 +7,25 @@ configure_iptables_firewall() {
 
     # Loop through each port and configure iptables rules
     for port in "${PORTS_ARRAY[@]}"; do
-        iptables -A INPUT -p tcp -m tcp --dport "$port" -m state --state NEW,ESTABLISHED -j ACCEPT >> "$LOG_FILE" 2>&1
+        # Add iptables rule for each port
+        if ! iptables -A INPUT -p tcp -m tcp --dport "$port" -m state --state NEW,ESTABLISHED -j ACCEPT >> "$LOG_FILE" 2>&1; then
+            log "${RED}Error configuring iptables rule for port $port.${NC}"
+            exit 1
+        fi
     done
 
-    iptables -A INPUT -i lo -j ACCEPT >> "$LOG_FILE" 2>&1
-    iptables -A INPUT -j DROP >> "$LOG_FILE" 2>&1
+    # Allow loopback traffic
+    if ! iptables -A INPUT -i lo -j ACCEPT >> "$LOG_FILE" 2>&1; then
+        log "${RED}Error configuring iptables rule for loopback traffic.${NC}"
+        exit 1
+    fi
 
-    log "${BLUE}Configuring iptables firewall$: ${GREEN}DONE${NC}"
-    echo -e "${BLUE}Configuring iptables firewall$: ${GREEN}DONE${NC}" >> report.txt
+    # Drop all other traffic (default policy)
+    if ! iptables -A INPUT -j DROP >> "$LOG_FILE" 2>&1; then
+        log "${RED}Error configuring iptables rule to drop all other traffic.${NC}"
+        exit 1
+    fi
+
+    log "${BLUE}Configuring iptables firewall: ${GREEN}DONE${NC}"
+    echo -e "${BLUE}Configuring iptables firewall: ${GREEN}DONE${NC}" >> report.txt
 }
